/** Challenge definitions (bundled at build time). Source of truth for frontend. */

export type AffinityType = 'strength' | 'agility' | 'wisdom' | 'balance';

export interface ChallengeDefinition {
    id: string;
    name: string;
    description: string;
    type: AffinityType;
    affinity: string;
    image: string;
    requirements: { stage: number; strength: number; agility: number; wisdom: number };
    maxDailyAttempts: number;
    maxScore: number;
    xpReward: { base: number; perPoint: number };
    enabled: boolean;
}

export const CHALLENGES: ChallengeDefinition[] = [
    {
        id: "chl_garden-pest-patrol",
        name: "Garden Pest Patrol",
        description: "Start your totem's journey by protecting the garden. Use your instinct and reflexes to smack down those pesky moles where they pop up.",
        type: "balance",
        affinity: "balance",
        image: "/challenges/first-path-challenge.jpg",
        requirements: { stage: 0, strength: 1, agility: 1, wisdom: 1 },
        maxDailyAttempts: 5,
        maxScore: 1000,
        xpReward: { base: 10, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_boulder-breaker",
        name: "Boulder Breaker",
        description: "Break a massive rock by timing your strikes correctly. Strength determines power and speed. Harder levels add resistance.",
        type: "strength",
        affinity: "strength",
        image: "/challenges/breaking-background.png",
        requirements: { stage: 0, strength: 10, agility: 5, wisdom: 5 },
        maxDailyAttempts: 5,
        maxScore: 2000,
        xpReward: { base: 20, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_totem-wrestling",
        name: "Totem Wrestling",
        description: "Push against a guardian spirit in a strength duel. Tap rapidly to overpower it. Strength affects endurance and resistance.",
        type: "strength",
        affinity: "strength",
        image: "/challenges/wrestling-ring-background.png",
        requirements: { stage: 1, strength: 13, agility: 5, wisdom: 5 },
        maxDailyAttempts: 5,
        maxScore: 2000,
        xpReward: { base: 20, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_rockfall-defense",
        name: "Rockfall Defense",
        description: "Block falling boulders by clicking in the right zones. Strength increases stamina for longer survival. Higher levels add unpredictable patterns.",
        type: "strength",
        affinity: "strength",
        image: "/challenges/rockfall-defense-background.png",
        requirements: { stage: 2, strength: 16, agility: 5, wisdom: 5 },
        maxDailyAttempts: 5,
        maxScore: 3000,
        xpReward: { base: 30, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_riverside-dodge",
        name: "Riverside Dodge",
        description: "Evade piranhas leaping from the river. Agility extends your reaction window, giving you more time to read each incoming strike.",
        type: "agility",
        affinity: "agility",
        image: "/challenges/Riverside-Background.png",
        requirements: { stage: 0, strength: 5, agility: 10, wisdom: 5 },
        maxDailyAttempts: 5,
        maxScore: 1000,
        xpReward: { base: 20, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_spirit-path",
        name: "Spirit Path Navigation",
        description: "Navigate a magical path of vanishing tiles, racing from start to finish before the ground disappears beneath you.",
        type: "balance",
        affinity: "balance",
        image: "/challenges/spiritpath-background.png",
        requirements: { stage: 1, strength: 1, agility: 1, wisdom: 1 },
        maxDailyAttempts: 5,
        maxScore: 2000,
        xpReward: { base: 20, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_spirit-labyrinth",
        name: "Spirit Labyrinth",
        description: "Navigate the fog-shrouded spirit labyrinth. Tap adjacent tiles to move through the maze. Find the exit before time runs out.",
        type: "balance",
        affinity: "balance",
        image: "/challenges/Fog-Maze-Cover.png",
        requirements: { stage: 2, strength: 1, agility: 1, wisdom: 1 },
        maxDailyAttempts: 5,
        maxScore: 3000,
        xpReward: { base: 30, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_aerial-ring-dive",
        name: "Aerial Ring Dive",
        description: "Fly through shifting rings in the air. Agility improves control. Missing too many rings voids the attempt.",
        type: "agility",
        affinity: "agility",
        image: "/challenges/aerial-ring-background.png",
        requirements: { stage: 1, strength: 5, agility: 13, wisdom: 5 },
        maxDailyAttempts: 5,
        maxScore: 2000,
        xpReward: { base: 20, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_spirit-dance",
        name: "Totem Spirit Dance",
        description: "Tap in rhythm with spirit drum beats. Agility determines timing accuracy. Harder levels add offbeat sections.",
        type: "agility",
        affinity: "agility",
        image: "/challenges/totem-spirit-background.png",
        requirements: { stage: 2, strength: 5, agility: 16, wisdom: 5 },
        maxDailyAttempts: 5,
        maxScore: 3000,
        xpReward: { base: 30, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_ancient-runes",
        name: "Ancient Runes Decoding",
        description: "Memorize and repeat glowing rune patterns. Wisdom increases memory retention and mistake tolerance. Higher levels add speed.",
        type: "wisdom",
        affinity: "wisdom",
        image: "/challenges/ancient-runes-background.png",
        requirements: { stage: 0, strength: 5, agility: 5, wisdom: 10 },
        maxDailyAttempts: 5,
        maxScore: 2000,
        xpReward: { base: 20, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_star-mapping",
        name: "Celestial Star Mapping",
        description: "Connect stars to form constellations. Wisdom provides hints and reduces errors. Higher difficulty means more complex patterns.",
        type: "wisdom",
        affinity: "wisdom",
        image: "/challenges/celestial-star-background.png",
        requirements: { stage: 1, strength: 5, agility: 5, wisdom: 13 },
        maxDailyAttempts: 5,
        maxScore: 2000,
        xpReward: { base: 20, perPoint: 0.01 },
        enabled: true,
    },
    {
        id: "chl_spirit-weaving",
        name: "Spirit Weaving Runes",
        description: "Align magical runes in the correct order. Incorrect placements disrupt the pattern. Wisdom slows instability.",
        type: "wisdom",
        affinity: "wisdom",
        image: "/challenges/spirit-weaving-background.png",
        requirements: { stage: 2, strength: 5, agility: 5, wisdom: 16 },
        maxDailyAttempts: 5,
        maxScore: 3000,
        xpReward: { base: 30, perPoint: 0.01 },
        enabled: true,
    },
];
