#!/usr/bin/env python3
"""
Synthesizes wisp grab + release SFX for the village wanderer interactions.

  - wisp-grab.mp3    sprite shimmer, played when a wanderer is grabbed
  - wisp-release.mp3 descending "wiz" sweep, played when it returns to path

Both files are short, low-volume one-shots designed to layer over the looping
village ambient without fighting it. Generates a 44.1 kHz mono PCM intermediate,
hands it to ffmpeg for mp3 encode, then deletes the wav so only the production
file ships. Mirrors the toolchain in tools/generate-village-ambient.py.

Run from repo root:
    python3 tools/generate-village-sfx.py
"""
from __future__ import annotations

import math
import shutil
import struct
import subprocess
import sys
import wave
from pathlib import Path

SAMPLE_RATE = 44100
OUT_DIR = Path(__file__).resolve().parent.parent / "public" / "sounds" / "village"
MP3_BITRATE = "96k"


# ---------------------------------------------------------------------------
# Wisp grab — sprite shimmer
# ---------------------------------------------------------------------------
# A bright ascending arpeggio + sparkle dust. Three sine voices in a major
# triad (E6/A6/E7), each with a gentle attack and a stretched exponential
# decay. A slow shimmer LFO modulates amplitude so the tone twinkles rather
# than sitting flat. Mixed quietly so the cue sits *over* the ambient instead
# of replacing it.
GRAB_DURATION = 0.55  # seconds
GRAB_NOTES = [
    # (freq Hz, start sec, gain, decay rate)
    (1318.5, 0.00, 0.16, 4.5),   # E6
    (1760.0, 0.05, 0.14, 4.0),   # A6
    (2637.0, 0.12, 0.10, 5.0),   # E7
]


def render_grab() -> list[float]:
    n = int(SAMPLE_RATE * GRAB_DURATION)
    out: list[float] = []
    # Sparkle dust: a tiny high-passed pulse train. Generated by xor'ing a fast
    # phase accumulator so it sounds gritty + glassy rather than tonal.
    sparkle_phase = 0
    sparkle_rate = 0.62  # gritty granular density
    sparkle_lp = 0.0
    for i in range(n):
        t = i / SAMPLE_RATE
        s = 0.0
        for freq, start, gain, decay in GRAB_NOTES:
            dt = t - start
            if dt < 0:
                continue
            # Short attack so it doesn't click; long-ish exp decay.
            attack = min(1.0, dt / 0.03)
            env = attack * math.exp(-dt * decay)
            # Slight pitch slide up at the start (50ms) gives the "twinkle in"
            # impression. After the slide, just the steady freq.
            slide = 1.0 if dt > 0.05 else 0.85 + 0.15 * (dt / 0.05)
            s += gain * env * math.sin(2 * math.pi * freq * slide * dt)
        # Shimmer LFO: 6 Hz amplitude modulation, 12% depth
        shimmer = 1.0 - 0.06 + 0.06 * math.sin(2 * math.pi * 6.0 * t)
        s *= shimmer
        # Sparkle dust — quiet, narrow, decays with the note envelope
        sparkle_phase = (sparkle_phase + 1) & 0xFFFF
        bit = 1 if (sparkle_phase * 41) & 0x100 else -1
        # Crude one-pole HP via difference with smoothed signal
        sparkle_lp = sparkle_lp * 0.7 + bit * 0.3
        sparkle = (bit - sparkle_lp) * 0.012 * math.exp(-t * 4.0) * sparkle_rate
        s += sparkle
        out.append(s)
    # Tail fade so the file ends in silence even if a voice is still ringing.
    fade_n = int(SAMPLE_RATE * 0.05)
    for i in range(fade_n):
        idx = n - fade_n + i
        out[idx] *= 1.0 - (i / fade_n)
    return out


# ---------------------------------------------------------------------------
# Wisp release — quiet spiraling drift back to the path
# ---------------------------------------------------------------------------
# Audio analogue of the on-screen return spiral (cos/sin orbit shrinking as the
# wisp glides back). Center pitch drops exponentially over the clip while a
# slower wobble modulates the pitch up/down at ~4 Hz — that wobble is what the
# ear reads as "spiraling around a moving point." Amplitude also tremolos with
# the spiral phase so each lap fades in and out, suggesting orbital distance.
# Lower base gain than v1 + a single soft voice (no octave body) so the cue
# sits well under the ambient bed and doesn't compete with the grab sparkle.
RELEASE_DURATION = 0.55
RELEASE_START_HZ = 1100.0
RELEASE_END_HZ = 340.0
RELEASE_WOBBLE_HZ = 4.0      # spiral laps per second — three laps over 0.75 s
RELEASE_WOBBLE_DEPTH = 0.18  # ±18% pitch around the descending center


def render_release() -> list[float]:
    n = int(SAMPLE_RATE * RELEASE_DURATION)
    out: list[float] = []
    # Phase accumulator for the wobbled sine — integrating instantaneous
    # frequency keeps the waveform phase-continuous even though `freq` itself
    # is sweeping AND wobbling.
    phase = 0.0
    for i in range(n):
        t = i / SAMPLE_RATE
        u = t / RELEASE_DURATION  # 0..1
        # Exponential center descent — natural "falling" pitch curve.
        center = RELEASE_START_HZ * (RELEASE_END_HZ / RELEASE_START_HZ) ** u
        # Spiral wobble: sine modulation on pitch. Multiplicative so the
        # depth stays musically consistent as the center moves down.
        wobble = 1.0 + RELEASE_WOBBLE_DEPTH * math.sin(2 * math.pi * RELEASE_WOBBLE_HZ * t)
        freq = center * wobble
        phase += 2 * math.pi * freq / SAMPLE_RATE
        # Amplitude tremolo locked to the wobble (cosine = 90° offset from
        # the pitch sine). Each spiral lap has a "swoop in / fade out"
        # amplitude curve reinforcing the orbital feel.
        tremolo = 0.6 + 0.4 * (0.5 + 0.5 * math.cos(2 * math.pi * RELEASE_WOBBLE_HZ * t))
        # Overall envelope: soft attack, gentle exponential decay across
        # most of the clip so the spiral trails off rather than cutting.
        if t < 0.020:
            env = t / 0.020
        else:
            env = math.exp(-(u - 0.05) * 2.6) if u > 0.05 else 1.0
        s = 0.11 * env * tremolo * math.sin(phase)
        out.append(s)
    # Tail fade so the file ends at zero amplitude regardless of phase.
    fade_n = int(SAMPLE_RATE * 0.04)
    for i in range(fade_n):
        idx = n - fade_n + i
        out[idx] *= 1.0 - (i / fade_n)
    return out


# ---------------------------------------------------------------------------
# Shared encode pipeline (mirrors tools/generate-village-ambient.py)
# ---------------------------------------------------------------------------
def normalize(samples: list[float], peak_target: float = 0.92) -> list[float]:
    peak = max((abs(s) for s in samples), default=0.0)
    if peak <= 0:
        return samples
    scale = peak_target / peak
    if scale >= 1.0:
        return samples
    return [s * scale for s in samples]


def write_wav(samples: list[float], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SAMPLE_RATE)
        frames = bytearray()
        for s in samples:
            v = max(-1.0, min(1.0, s))
            frames += struct.pack("<h", int(v * 32767))
        w.writeframes(bytes(frames))


def encode_mp3(wav: Path, mp3: Path) -> bool:
    if not shutil.which("ffmpeg"):
        print("ffmpeg not found on PATH; skipping mp3 encode.", file=sys.stderr)
        return False
    subprocess.run(
        [
            "ffmpeg", "-y", "-loglevel", "error",
            "-i", str(wav),
            "-codec:a", "libmp3lame",
            "-b:a", MP3_BITRATE,
            "-ac", "1",
            str(mp3),
        ],
        check=True,
    )
    return True


def emit(name: str, samples: list[float]) -> None:
    wav = OUT_DIR / f"{name}.wav"
    mp3 = OUT_DIR / f"{name}.mp3"
    write_wav(normalize(samples), wav)
    if encode_mp3(wav, mp3):
        print(f"Wrote {mp3} ({mp3.stat().st_size / 1024:.0f} KB)")
        wav.unlink()
    else:
        print(f"Wrote {wav} ({wav.stat().st_size / 1024:.0f} KB) — install ffmpeg for mp3", file=sys.stderr)


def main() -> int:
    print(f"Generating village SFX @ {SAMPLE_RATE} Hz mono…")
    emit("wisp-grab", render_grab())
    emit("wisp-release", render_release())
    return 0


if __name__ == "__main__":
    sys.exit(main())
